-- Create dividend_history table if not exists or needs update
-- Note: User might need to drop existing one if schema changed or alter it.

create table if not exists dividend_history (
  id bigint generated by default as identity primary key,
  stock_id uuid references stocks(id) on delete cascade,
  date_str text, -- e.g. "2025/12"
  amount numeric,
  is_increase boolean,
  change_pct numeric,
  comparison_amount numeric,
  created_at timestamp with time zone default now()
);

-- Enable RLS
alter table dividend_history enable row level security;
-- create policy "Public Access" on dividend_history for select using (true);
